#!/bin/bash
#
# Writes Config/Local.xcconfig (gitignored) so the project signs with YOUR
# free Apple Developer "Personal Team" instead of upstream's team.
#
# Run it once, after signing in to Xcode with your Apple ID
# (Xcode > Settings > Accounts):
#
#     ./scripts/setup-signing.sh
#
# Optional arguments:
#     ./scripts/setup-signing.sh --team ABCDE12345     use this team ID
#     ./scripts/setup-signing.sh --prefix com.example  change bundle ID prefix
#     ./scripts/setup-signing.sh --force               overwrite existing file
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/Config/Local.xcconfig"

TEAM=""
PREFIX="com.mehtavishad"
FORCE=0

while [ $# -gt 0 ]; do
    case "$1" in
        --team)   TEAM="$2"; shift 2 ;;
        --prefix) PREFIX="$2"; shift 2 ;;
        --force)  FORCE=1; shift ;;
        -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [ -f "$OUT" ] && [ "$FORCE" -ne 1 ]; then
    echo "Config/Local.xcconfig already exists:"
    echo
    sed 's/^/    /' "$OUT"
    echo
    echo "Nothing changed. Re-run with --force to replace it."
    exit 0
fi

# Look for the team Xcode registered when you signed in. Xcode has stored
# this under different preference keys over the years, so walk all of them
# and collect anything shaped like a team.
find_teams() {
    defaults export com.apple.dt.Xcode - 2>/dev/null | python3 -c '
import plistlib, sys
try:
    prefs = plistlib.loads(sys.stdin.buffer.read())
except Exception:
    sys.exit(0)

seen = {}
def walk(node):
    if isinstance(node, dict):
        tid = node.get("teamID") or node.get("teamId")
        if isinstance(tid, str) and len(tid) == 10:
            free = bool(node.get("isFreeProvisioningTeam"))
            name = node.get("teamName") or node.get("name") or ""
            seen[tid] = (free or seen.get(tid, (False, ""))[0], name)
        for value in node.values():
            walk(value)
    elif isinstance(node, list):
        for value in node:
            walk(value)
walk(prefs)

# Personal (free) teams first.
for tid, (free, name) in sorted(seen.items(), key=lambda kv: not kv[1][0]):
    print(f"{tid}\t{1 if free else 0}\t{name}")
'
}

if [ -z "$TEAM" ]; then
    TEAMS="$(find_teams || true)"
    COUNT="$(printf '%s' "$TEAMS" | grep -c . || true)"

    if [ "$COUNT" -eq 0 ]; then
        cat <<'MSG'
Could not find a signing team in Xcode's settings.

  1. Open Xcode.
  2. In the menu bar: Xcode > Settings...  (or press Cmd + ,)
  3. Click the "Accounts" tab.
  4. Click "+" at the bottom left, choose "Apple ID", sign in.
  5. You should now see your name with "(Personal Team)" under it.
  6. Run this script again.

If you are signed in and still see this, ask Claude to look up the team
ID, then run:  ./scripts/setup-signing.sh --team YOURTEAMID
MSG
        exit 1
    fi

    PERSONAL="$(printf '%s\n' "$TEAMS" | awk -F'\t' '$2 == "1"')"
    if [ "$COUNT" -gt 1 ] && [ "$(printf '%s' "$PERSONAL" | grep -c . || true)" -eq 1 ]; then
        TEAMS="$PERSONAL"
        COUNT=1
    fi

    if [ "$COUNT" -gt 1 ]; then
        echo "Found more than one team:"
        printf '%s\n' "$TEAMS" | awk -F'\t' '{ printf "    %s  %s%s\n", $1, $3, ($2 == "1" ? "  (Personal Team)" : "") }'
        echo
        echo "Re-run with the one you want:  ./scripts/setup-signing.sh --team TEAMID"
        exit 1
    fi

    TEAM="$(printf '%s' "$TEAMS" | cut -f1)"
    NAME="$(printf '%s' "$TEAMS" | cut -f3)"
    echo "Using team $TEAM ${NAME:+($NAME)}"
fi

if ! printf '%s' "$TEAM" | grep -Eq '^[A-Z0-9]{10}$'; then
    echo "\"$TEAM\" does not look like a team ID (10 letters/digits)." >&2
    exit 2
fi

cat > "$OUT" <<EOF
// Per-machine signing overrides. Gitignored — never commit this file.
// Generated by scripts/setup-signing.sh on $(date +%Y-%m-%d).

DEVELOPMENT_TEAM = $TEAM
BB_BUNDLE_ID_PREFIX = $PREFIX
BB_APP_GROUP = group.$PREFIX.enlink
EOF

echo
echo "Wrote Config/Local.xcconfig:"
sed 's/^/    /' "$OUT"
echo
echo "App bundle ID:    $PREFIX.BetterBlue"
echo "Widget bundle ID: $PREFIX.BetterBlue.Widget"
